# Generated by Django 3.0 on 2019-12-16 09:35

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MyPage', '0002_auto_20191216_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='static/images/post'),
        ),
    ]
